[package]
name = "mwlint-wasm"
version = "0.1.0"
authors = ["Valentin Roland <valentin@vroland.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
mediawiki_parser = "0.3"
mwlint = { path = "../" }
lazy_static = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2"
serde_derive = "1.0"
serde = "1.0"
